name: Release
on:
  push:
    tags:
      - 'v*'
  pull_request:

jobs:

  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18
      - name: run goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
