name: Release
on:
  push:
    tags:
      - 'v*'
  pull_request:

jobs:

  deploy:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v3

      - name: Lint Go Code
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go install golang.org/x/lint/golint@latest
          make lint

      - name: Get Tag Version
        run: |
          echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "tag=${{ github.ref_name }}"

      - name: Build Tar
        run: make tar

      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
          files: |
            ./_output/vine-darwin-arm64-${{ github.ref_name }}.tar.gz
            ./_output/vine-darwin-amd64-${{ github.ref_name }}.tar.gz
            ./_output/vine-linux-amd64-${{ github.ref_name }}.tar.gz
            ./_output/vine-linux-arm64-${{ github.ref_name }}.tar.gz
            ./_output/vine-windows-amd64-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
